env_name: "testgame"
obs_type: "image"
obs_size: [96, 96, 3]
seed: 0 

# Training params
learning_rate: 0.002
learning_rate_decay: 0.9
weight_decay: 0.0001
root_dirichlet_alpha: 0.25
explore_frac: 0.25
val_weight: 2
discount: 0.988054
n_batches: 60
batch_size: 5
rollout_depth: 5
reward_depth: 5
<<<<<<< HEAD
buffer_size: 20
consistency_loss: True
=======
buffer_size: 1 
consistency_loss: False
>>>>>>> origin/testgame
consistency_weight: 0.5
reanalyse: True
reanalyse_n: 1
grad_clip: 1
last_n_frames: 4  
frame_skip: 4
prior_weight: 1
<<<<<<< HEAD
=======
dropout: 0.2

temp1: 1000
temp2: 2000
>>>>>>> origin/testgame

# Replay params
priority_replay: True
priority_alpha: 1
priority_beta: 1

# Model params
latent_size: 20
channel_list: [16, 32]
support_width: 25
n_simulations: 10

# Setup params  
log_dir: "runs"
<<<<<<< HEAD
log_name: "last"
=======
log_name: "testgame_low"
>>>>>>> origin/testgame
debug: False
render: False 
print_simple: True
max_games: 400
temp_time: 50

max_frames: 3000