env_name: "CartPole-v1"
obs_type: "discrete"
seed: 0

# Training params
learning_rate: 0.02
learning_rate_decay: 0.9
weight_decay: 0.0001
root_dirichlet_alpha: 0.25
explore_frac: 0.25
val_weight: 0.25
discount: 0.997
n_batches: 100
batch_size: 30
rollout_depth: 5
reward_depth: 80
buffer_size: 50
consistency_loss: True
consistency_weight: 0.5
reanalyse: True
reanalyse_n: 1
grad_clip: 0 # 0 indicates no clipping
prior_weight: 1

# Replay params
priority_replay: False
priority_alpha: 1
priority_beta: 1

# Model params
latent_size: 20
support_width: 25
n_simulations: 40

# Setup params  
log_dir: "runs"
log_name: "None"
debug: True
render: True
print_simple: True
max_games: 1000
temp_time: 20

max_frames: 1000