env_name: "Breakout-v0"
obs_type: "image"
seed: 0 

# Training params
learning_rate: 0.003
learning_rate_decay: 0.9
weight_decay: 0.0001
root_dirichlet_alpha: 0.25
explore_frac: 0.25
val_weight: 2
discount: 0.997
n_batches: 60
batch_size: 5
rollout_depth: 5
reward_depth: 100
buffer_size: 100
consistency_loss: True
consistency_weight: 0.5
reanalyse: True
reanalyse_n: 1
grad_clip: 1
last_n_frames: 4
prior_weight: 1

# Replay params
priority_replay: True
priority_alpha: 1
priority_beta: 1

# Model params
latent_size: 20
repr_channels: 12
support_width: 25
n_simulations: 20

# Setup params  
log_dir: "runs"
log_name: "last"
debug: True
render: True
print_simple: True
max_games: 400
temp_time: 50

max_frames: 3000