env_name: CartPole-v0
latent_size: 20
log_dir: runs
val_weight: 0.25
n_simulations: 100
buffer_size: 100
learning_rate: 0.003
learning_rate_decay: 0.9
discount: 0.997
n_batches: 100
batch_size: 10
support_width: 10