env_name: "BreakoutNoFrameskip-v4"
obs_type: "image"

# Training params
learning_rate: 0.02
learning_rate_decay: 0.9
weight_decay: 0.1
root_dirichlet_alpha: 0.25
explore_frac: 0.25
val_weight: 0.25
discount: 0.997
n_batches: 100
batch_size: 10
rollout_depth: 5
reward_depth: 5
buffer_size: 100
consistency_loss: True
consistency_weight: 2
reanalyse: True
grad_clip: 10

# Replay params
priority_replay: False
priority_alpha: 1
priority_beta: 1

# Model params
latent_size: 20
support_width: 25
n_simulations: 20

# Setup params  
log_dir: "runs"
log_name: "None"
debug: True
render: True
print_simple: True
max_games: 400
temp_time: 50

max_frames: 3000  