# Basic params
env_name: "Acrobot-v1"
obs_name: "acrobot"
obs_type: "discrete"
seed: 0

# Setup params  
log_dir: "runs"
log_name: "None"
load_buffer: False
debug: False
train_speed_profiling: False
get_batch_profiling: False
render: True
print_simple: True
max_games: 500 # Total number of games before training is ended
max_total_frames: 200000
max_frames: 1000 # Maximum frames for a single game before it is cut short
try_cuda: False # Whether to use cuda if available (makes training slower on cartpole)


# Model params
latent_size: 20
support_width: 25
n_simulations: 40

# Training params
learning_rate: 0.02
learning_rate_decay: 0.9
weight_decay: 0.0001
grad_clip: 1 # 0 interpreted as no clipping
val_weight: 0.25
batch_size: 30

# Search params
root_dirichlet_alpha: 0.25
explore_frac: 0.25
discount: 0.997
n_batches: 100
rollout_depth: 5
reward_depth: 30
buffer_size: 200

# Priority replay params
priority_replay: False
priority_alpha: 1
priority_beta: 1

# Temperature schedule
temp1: 2000 # Steps after which temperature is dropped to 0.5
temp2: 5000 # Steps after which temperature is dropped to 0.25
temp3: 15000 # Steps after which temperature is dropped to 0

# Reanalyse
reanalyse: True
reanalyse_n: 1
prior_weight: 1
momentum: 0.9

## EfficientZero Additions
# Value prefix
value_prefix: False
lstm_hidden_size: 16

# Off policy correction
off_policy_correction: True
tau: 0.3
reward_steps: 1000
total_training_steps: 100_000

# Consistency loss
consistency_loss: True
consistency_weight: 0.5