# Basic params
env_name: "BreakoutNoFrameskip-v4"
obs_type: "image"
seed: 0
obs_size: [96, 96, 3]

# Setup params  
log_dir: "runs"
log_name: "None"
load_buffer: False
debug: False
train_speed_profiling: False
render: False
print_simple: True
max_games: 500 # Total number of games before training is ended
max_total_frames: 100000
max_frames: 3000 # Maximum frames for a single game before it is cut short
n_simulations: 10

# Model params
latent_size: 20
channel_list: [16, 32]
support_width: 25
last_n_frames: 4   # image only
dropout: 0.5      # image only

# Training params
learning_rate: 0.02
learning_rate_decay: 0.9
weight_decay: 0.0001
grad_clip: 1 # 0 interpreted as no clipping
val_weight: 0.25
batch_size: 30

# Search params
root_dirichlet_alpha: 0.25
explore_frac: 0.25
discount: 0.997
n_batches: 100
rollout_depth: 5
reward_depth: 30
buffer_size: 200

# Priority replay params
priority_replay: True
priority_alpha: 1
priority_beta: 1

# Temperature schedule
temp1: 10000 # Steps after which temperature is dropped to 0.5
temp2: 20000 # Steps after which temperature is dropped to 0.25
temp3: 100000 # Steps after which temperature is dropped to 0

# Reanalyse
reanalyse: True
reanalyse_n: 1
prior_weight: 1
momentum: 0.9

## EfficientZero Additions
# Value prefix
value_prefix: True
lstm_hidden_size: 512
val_prefix_size: 32
reward_channels: 16

# Off policy correction
off_policy_correction: True
tau: 0.3
reward_steps: 1000
total_training_steps: 100_000

# Consistency loss
consistency_loss: True
consistency_weight: 0.5